### ISSUE TITLE
github is starting to M$uck -&- Stop hating master

### ISSUE THREAD

**Issue by TinCanTech** [TinCanTech/easy-tls#144]
I guess gitlab is next .. ?

_Firefox blocked fingerprinter on this web page - https://services.github.com/_

**Comment by houmie** [comment]
Oh no. Please not GitLab. :)  OpenSource projects should really stay on GitHub.

**Comment by TinCanTech** [comment]
With Microsoft owning github, this is no longer the place for open source projects.

I have used gitlab before and I know the feeling, it is a bit clumsy by comparison. However, it is the site of choice for Openvpn developers.  I have been surprised by how quickly they switched over to gitlab, following MS buy-out of github.

**Comment by houmie** [comment]
I see where you're coming from. I'm also traditionally anti Microsoft. I wouldn't touch it with a barge pole. ;)
However Github wasn't touched since the take over and still everything seems to continue to be predominantly on Github. 

I actually switched recently from Gitlab to Github, due to the pain they caused me. They keep changing features without much thought and often they are buggy.

Remember how they changed the Deployment Keys from ```Settings -> Repo``` to ```Settings -> CI``` and nobody could find it. After six months they switched it back again.  They are clueless.

There is also a nasty bug, that made me go nuts. The same section with deployment keys could bug out and stop showing the keys, if you have over 20 keys stored in there.  The web call times out.

**Comment by TinCanTech** [comment]
I have a gitlab account already and I know what you mean.

I created a simple test repo and then tried to delete it. gitlab refused to delete it for two weeks ..

**Comment by TinCanTech** [comment]
Mark my words.

Github will have banner advertising before 2021 is out..

**Comment by houmie** [comment]
I hope not.  I'm definitely not an MS person.  But they have done recently some good moves with Visual Studio Code and GitHub. Azure Pipelines for CI is also nice.  I hope they keep the productive trend and don't fall into the abyss. :)

**Comment by TinCanTech** [comment]
Prepare: "_To have Thy bubble popped_"

**Comment by xinthose** [comment]
Your repo was grandfathered in with `master` instead of `main` at least.  I don't know why GitHub spent lots of their own money and time on something trivial like that.

**Comment by houmie** [comment]
Couldn't agree more. This silly issue has disrupted our deployment process multiple times across several repos.  I wonder how many hours have been worldwide wasted collectively on this silly issue.  This is when well-intended politics gets shoved down your throat, without any real benefit. :)

**Comment by TinCanTech** [comment]
It's a stupid _woke_ joke .. perpetrated by _butt-hurt interfering busy-body hypocrites_.

I bet none of them have guts to tell **Mastercard** and I bet some of them even have one..

**Comment by xinthose** [comment]
I do like that they moved to free private repositories.  I will not pay for their service again.

**Comment by houmie** [comment]
That's a good one. I never thought of Mastercard this way.  Oh god...that comes next. :-D

**Comment by TinCanTech** [comment]
Actually, I have lost access to all my gmail accounts (x13), including tincanteksup@gmail.

MS/github actually did a really good job of re-establishing my access here on github.

Before you ask, lost my mobile .. goolag says: NO.

**Comment by houmie** [comment]
I'm sorry to hear that mate. I bet you had a two factor authentication enabled and didn't have the backup codes saved somewhere, right? I'm glad GitHub was more helpful than Google.  You see not all that bad. ;-)

**Comment by TinCanTech** [comment]
I was fed-up of goolag anyway, so I just moved dooms-day ahead by a few months ;-)

**Comment by TinCanTech** [comment]
WRT `master/slave`, I can understand why people don't like the term `slave` but I think their over-reaction to `master` is dumb. Let's be honest, I am labelled as the `owner` of this repository and all `slaves` were `owned`, so how are they going to _whisk_ that away ?

So when it comes to the repository I would personally vote for `master/copy`, that is **exactly** what it is.
And as for `owner` .. seems like if you own something you are oppressing somebody else (Homeowner->Landlord), so leave it be. Unless somebody can suggest a suitable alternative .. ?

**Comment by TinCanTech** [comment]
Windows-Github-Desktop is distributed with alternative data streams that cannot be copied -- Try it for yourself.

**Comment by TinCanTech** [comment]
Phasing out `owner` has already started .. I am now `Maintainer` on `Discussions` ..
