### ISSUE TITLE
Inline-index checks must detect manually moved/removed files

### ISSUE THREAD

**Issue by TinCanTech** [TinCanTech/easy-tls#147]
Thanks to @houmie and his help testing, we discovered a weakness in the integrity of the inline-index.

If a key or inline file is moved/removed manually then the index will cease to function as intended.

**Comment by TinCanTech** [comment]
@houmie if you get some time, I would like you to try and break it again! :wink:

**Comment by houmie** [comment]
@TinCanTech sure, no problem. :) I will tackle it in the coming weekend, if you don't mind.  I've set a reminder in my calendar.

**Comment by houmie** [comment]
So much has been referenced here, is something ground breaking changing? :D

**Comment by TinCanTech** [comment]
I created a Master-index to watch over the entire Easy-TLS data set.

It is a background process which will not get much attention until it goes wrong or a user manually changes something.
