### ISSUE TITLE
How to see the current active custom group? 

### ISSUE THREAD

**Issue by houmie** [TinCanTech/easy-tls#150]
Hey mate,

I was testing a bit more today.  

After creating a custom group with ```--batch``` how can verify if it was actually created?
Is there a way to see the current active custom group?

```./easytls --batch config custom.group tg```

Thanks

**Comment by TinCanTech** [comment]
Use `./easytls config` to view the current settings.

**Comment by houmie** [comment]
Sorry for late confirmation. Yes, that works.
