### ISSUE TITLE
Collaboration - My Corona

### ISSUE THREAD

**Issue by TinCanTech** [TinCanTech/easy-tls#156]
**I have NEVER worn a mask and never will.
I will NEVER take _Their_ placebo.
I go shopping Every-Single-Day on a busy London-UK street.
If you were to stand two meters away from everybody on a bus then you would be outside the bus.
(There is an _Essex Girl_ joke in there: And she still believes it is two meters long!)
Nobody EVER does "_social distancing_" because they do not understand how far two meters is.**

I am a "_high risk_" category, in this "_Event Sociological_"..

Just in case COVID-foo actually does get me then I need a second or so ..

Make me an offer !

You are welcome to believe in what-ever non-séance or "_God_" that you prefer ..

**Comment by TinCanTech** [comment]
Some simple mathematics based on _Their_ figures:
- Covid-19 global death rate is approximately ~1 in 50. ~2%.

**Before Global Lock-down**:
- 1.5 million people died of COVID-19 (Apparently)

**Which means**:
- 1,500,000 * 50 = 75,000,000 people were exposed to COVID-19

**Assuming that each of those 75 million people have/had friends and family**:
- It is safe to assume that 6 * 75 Million = 450,000.000 people were exposed to COVID-19
- Let's just round that up to an easy Half a Billion people were exposed to COVID-19
- **Before Global Lock-down**.

**The killer blow is this**:
- **5 Days After** the BBC announced an approximate 9% dip in The Global Financial Sector
- That is when They locked us away .. and **not** a day before.

If you don't believe me then look it up for yourself.

**Comment by TinCanTech** [comment]
Official figures for COVID-19 appropriated deaths in 2020 was ,in fact, only 1.5 million people more.

3 million official deaths by COVID-19 in Total .. Out of 8 Billion. **0.0375%**

Suicide kills more than that.

**Comment by TinCanTech** [comment]
Now then, you might be thinking "_Lock-down worked really well_"
So what happens when they end lock-down and one person still has COVID-19 ... ?

So punk, do you still feel safe ?

**Comment by Pippin1st** [comment]
https://www.aier.org/article/the-lockdown-paradigm-is-collapsing/

;)
