### ISSUE TITLE
github CI - Create a Windblows test

### ISSUE THREAD

**Issue by TinCanTech** [TinCanTech/easy-tls#163]
Have at it!

(If they ever invent time travel then I volunteer to go back and _Terminate_ Bill .. before it's too late)

**Comment by TinCanTech** [comment]
Does anybody know how to configure a Windows github CI runner ?

Not sure if anybody else is allowed to see this:
https://support.github.com/ticket/personal/0/1110973

**Comment by TinCanTech** [comment]
Sorry for all the failure notice spam .. Windblows really does blow on Github-CI.

This is the straw that finally broke the donkeys' back:
-  `inline_serial="$("$EASYTLS_GREP" '^# X509 serial: .*$' "$inline_file")"`
For what-ever reason, Windblows 2016 & 2019 fail to `grep` a serial number but it works everywhere else ..

**Comment by wiscii** [comment]
Closed via https://github.com/TinCanTech/easy-tls/commit/1f3528ed90ed8b4028a0076971e3d9b99cc06557

**Comment by wiscii** [comment]
Why _Microsoft are to computers what fur-balls are to cats_!

http://www.fourmilab.ch/webtools/demoroniser/
