### ISSUE TITLE
Unrecognized option or missing or extra parameter(s) in tun0-conf:318: tls-crypt-v2

### ISSUE THREAD

**Issue by keithknea** [TinCanTech/easy-tls#170]
The server version is OpenVPN 2.4.7, but I am getting this error on the server when I put the tls-crypt-v2 inline on the .conf. Thanks for the help

**Comment by TinCanTech** [comment]
> The server version is OpenVPN 2.4.7,

You require OpenVPN 2.5 to use `--tls-crypt-v2`
