### ISSUE TITLE
init-tls throws Missing openssl config

### ISSUE THREAD

**Issue by houmie** [TinCanTech/easy-tls#182]
I came across a strange issue today.

I'm not sure if this is because of a latest update or is it because I have also OpenSSL installed on the server.

```
wget https://www.openssl.org/source/openssl-1.1.1k.tar.gz
tar -zxvf openssl-1.1.1k.tar.gz
cd openssl-1.1.1k/
./config
make
sudo make install
sudo ldconfig
```

When I do:

```
/etc/openvpn/easy-rsa$ sudo ./easytls init-tls

Easy-TLS version: 2.1/
ERROR: Missing openssl config:  * https://raw.githubusercontent.com/TinCanTech/easy-tls/master/easytls-openssl.cnf
```

Is this a new feature? How do I configure it?

Thank you,

**Comment by TinCanTech** [comment]
Yes, it is a new feature.  All you need to do is copy that file to your `easyrsa/easytls` directory.

It will be used by `easytls` to build `self-signed` certificates for use with Openvpn `Peer-fingerprint` mode.

Thanks for testing!

**Comment by houmie** [comment]
Sure, It seems ```easyrsa/easytls``` is a file. Are you sure this is meant to be a directory?

**Comment by houmie** [comment]
Ah I think I got it. You mean:

```
cp ~/easy-tls/easytls-openssl.cnf /etc/openvpn/easy-rsa/
```

**Comment by TinCanTech** [comment]
Sorry, I was not clear.  Download the file from the url provided to the directory that you have installed `easyrsa` and `easytls`.  Leave the name as is `easytls-openssl.cnf`.

**Comment by houmie** [comment]
Yes, Now I can do:

```
/etc/openvpn/easy-rsa$ sudo ./easytls init-tls

WARNING!!!

You are about to remove the EASYTLS_PKI at: /etc/openvpn/easy-rsa/pki/easytls
and initialize a fresh TLS PKI here.

  Type the word 'yes' to continue, or any other input to abort.

  Confirm removal: yes


config-file updated: ca.id = 9968BFD56CABD152679D6FC5245F0AF7D3E4F2C42986603D2FE55E69CCC0C5C0

Saved CA Identity: /etc/openvpn/easy-rsa/pki/easytls/data/easytls-ca-identity.txt

init-tls complete; you may now create TLS keys and .inline files.
  Your newly created TLS dir is:

    /etc/openvpn/easy-rsa/pki/easytls

To configure your Easy-TLS custom group now, use:

    'easytls config custom.group YOUR_GROUP'

```

It works. Thanks

**Comment by TinCanTech** [comment]
In your case, you should have the file `/etc/openvpn/easy-rsa/easytls-openssl.cnf`

It will not interfere with `easy-rsa` and is only used by `easytls` in `no-ca` mode.

**Comment by TinCanTech** [comment]
If you feel like you can help make improvements, I am very happy to accept PRs * _nudge nudge_ *

**Comment by CallousComputer** [comment]
Hello?
I found a old tutorial to install openVPN on the internet , which used your tool, but it told me to download two files
easytls and easytls-openssl.cnf
