### ISSUE TITLE
Hello! there is an openvpn server, how can I make the server work with tls-crypt-v2

### ISSUE THREAD

**Issue by mercik** [TinCanTech/easy-tls#216]
Hello! there is an openvpn server, how can I make the server work with tls-crypt-v2

**Comment by TinCanTech** [comment]
This is the first step:
https://github.com/TinCanTech/easy-tls/wiki/05-=-Quick-Start-Normal-mode

**Comment by TinCanTech** [comment]
You cannot use TLS-Crypt-V2 keys _without changing_.

What you must do is:
- Install Easy-TLS into the Easy-RSA PKI directory which the angristan installer created.
- Use Easy-TLS to generate new TLS-Crypt-V2 keys and inline files.
- Use the inline files created above to update your VPN server and client configuration files.

Start by reading the **wiki** link above.

**Comment by mcharyyev** [comment]
Hey TInaCanTech

please, can you teach me how to set up TLS-Crypt-V2 with angristan openvpn script?

**Comment by TinCanTech** [comment]
https://github.com/TinCanTech/easy-tls/wiki/cheatSheet
