### ISSUE TITLE
Running the easytls-client-connect.sh on Windows 10

### ISSUE THREAD

**Issue by Mahaaveer** [TinCanTech/easy-tls#233]
I am having a hard time running easytls-client-connect.sh script on windows 10. WSL is enabled and on latest windows build.

Config file:
```
script-security 2
client-connect 'easytls-client-connect.sh -v -k -t=temp'
```

From the Logs:
env_block: add PATH=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem
WARNING: Failed running command (--client-connect): returned error code 255
PUSH: Received control message: 'PUSH_REQUEST'
Delayed exit in 5 seconds
'AUTH_FAILED' (status=1)

Tried running it as .bat , still returned the same error. 
Man page says :  255 - BUG Disallow connection, die() exited with default error code.
Is it bug in the code ?

Thanks, hoping to get it work :)

**Comment by TinCanTech** [comment]
Use this:
```
script-security 2
client-connect 'easytls-client-connect.sh -v -a'
```
Also, take a look in `C:\Windows\Temp\easytls-888888-client-connect.log` for details.

**Comment by Mahaaveer** [comment]
> Use this:
> 
> ```
> script-security 2
> client-connect 'easytls-client-connect.sh -v -a'
> ```
> 
> Also, take a look in `C:\Windows\Temp\easytls-888888-client-connect.log` for details.

Using the above arguments resulted in same error. 
and there is no log file with prefix 'easytls' in Windows/Temp

**Comment by TinCanTech** [comment]
Hi,

when you first opened this issue you mentioned using `.bat` files to launch the server script, however, Easy-TLS no longer ships those `.bat` files and has not done so for some time.  I suggest you clean your old directory of old Easy-TLS files and download a fresh install. I recommend you clone this repo from git and then copy over the scripts to your Easy-RSA working folder.

I also notice that you have downloaded the latest version (2.6) and you have a new error.  One of the reasons for your new error is that the `.inline` file has the wrong data in it.  So, update `easytls` and create a new `.inline` file.

And be aware .. you are using highly experimental scripts on your server, so you need to pay close attention to the software you are using and keep up to date and informed.

**Comment by Mahaaveer** [comment]
> Hi,
> 
> when you first opened this issue you mentioned using `.bat` files to launch the server script, however, Easy-TLS no longer ships those `.bat` files and has not done so for some time. I suggest you clean your old directory of old Easy-TLS files and download a fresh install. I recommend you clone this repo from git and then copy over the scripts to your Easy-RSA working folder.
> 
> I also notice that you have downloaded the latest version (2.6) and you have a new error. One of the reasons for your new error is that the `.inline` file has the wrong data in it. So, update `easytls` and create a new `.inline` file.
> 
> And be aware .. you are using highly experimental scripts on your server, so you need to pay close attention to the software you are using and keep up to date and informed.

Here's what I did:

1)  Fresh install Openvpn, easyrsa, generate new keys, and easytls 2.5, generate new keys and inline

This time the easytls script did work however, hwaddr mismatch error even though logs show they are the same! The addr being pushed by the client and checked for are equal (to make sure i did not enter it wrong,  i created another fresh key by copy/pasting the hwaddr  from the easytls error log) . Still wont work. 

2)  Fresh install Openvpn, easyrsa, generate new keys, and easytls 2.6, generate new keys and inline

ERROR: STACK_DOWN_PART_ERROR

I understand that it is a experimental script, just overwhelmed and excited by the potential security the script offers :)
This is a awesome project and idea. Thanks for developing it

**Comment by TinCanTech** [comment]
The error you have should not occur, so I have to look deeper into this.

As a temporary measure, you can create a file in the directory your server runs from (`/progra~1/Openvpn/Config` or `/Users/$youruser/openvpn/config`) called `easytls-client-connect.vars`.  Add these lines to the file:
```
EASYTLS_VERBOSE=1
ENABLE_STACK=1
```
and try again..

There is also a template file `easytls-client-connect.vars-example` which shows all the dynamic settings available.

**Comment by TinCanTech** [comment]
You also need `easytls-cryptv2-verify.vars` with the same lines as above.

**Comment by TinCanTech** [comment]
Here, the problem is **not** _stacking_ new client connections during TLS-Crypt-V2-verify and, subsequently, **not** _un-stacking_ correctly during client-connect.

This is mainly due to me not deciding on the safest approach, yet.  But it looks like I shall enable stacking by default.

**Comment by Mahaaveer** [comment]
Yes !! Got it working with version (2.6) by adding the `ENABLE_STACK=1` to the vars files.

A big Thumbs up to you ! This is one awesome project that can enable small users with unmatched security. Keep developing it if you have ideas in mind.

Thanks Again!

**Comment by TinCanTech** [comment]
@Mahaaveer Thank you!

**Comment by TinCanTech** [comment]
For future reference: _stacking_ is now enabled by default.
