### ISSUE TITLE
HW-ADDR LOCK  for Android

### ISSUE THREAD

**Issue by tkmw1985** [TinCanTech/easy-tls#235]
All is good, but hw-addr lock function which is provided by inter active menu installing correctly.  But,  it seems to not working with android apps ?

**Comment by TinCanTech** [comment]
Android does not supply a usable hardware address, due to privacy concerns.

Therefore, Android cannot use hardware address lock down.

However, Android can still use TLS-Crypt-V2 Keys.

**Comment by TinCanTech** [comment]
I would be interested to see your server log at `--verb 4` showing your Android connecting..

**Comment by tkmw1985** [comment]
Thank u for ur answer. I tested on official Openvpn app with Openvpn Access Server and they have script written in python after executing this script we can add manually 2 hw-addr to lock and HW-ADDR lock work as expected. But, yes it seems to android does not supply usable hardware address. To know correct hw-addr we need start official app and look in to log  and find correct hw-addr then copy it and apply via script !

**Comment by TinCanTech** [comment]
As I said, I would be curious to see what data your phone does push as a hardware address.

**Comment by tkmw1985** [comment]
https://paste.centos.org/view/bfc471ca

Loaded log from official openvpn app with --verb 4 flag !

**Comment by tkmw1985** [comment]
Is this log ok ? Or you need from server side log ? If you need i can do it but i do not know so much in unix commands.

**Comment by TinCanTech** [comment]
According to you log, your client pushed the following to the server:
```
Peer Info:
IV_VER=3.git::662eae9a:Release
IV_PLAT=android
IV_IPv6=0
IV_AUTO_SESS=1
IV_GUI_VER=net.openvpn.connect.android_3.2.5-7182
IV_SSO=openurl
IV_HWADDR=64:65:30:39:34:66:39
IV_SSL=OpenSSL 1.1.1j  16 Feb 2021
```
If `IV_HWADDR=64:65:30:39:34:66:39` is the real MAC address of this device the Hardware-Lockdown will work.  However, I have been informed that, due to genuine privacy concerns, that string is randomized ..

Try restarting your device and reconnect to your VPN and see if that value changes.

**Comment by tkmw1985** [comment]
Here in my smartphone in wi-fi settings has a function set  device own mac address or set randomized. 

What i did tested both of them and  result same hw-addr pushed !

**Comment by TinCanTech** [comment]
If you use randomise then it will send a random address.
