### ISSUE TITLE
How to use a config file in Windows

### ISSUE THREAD

**Issue by xinthose** [TinCanTech/easy-tls#258]
Hello.  Is there any documentation for using a config file for `easytls`?  I need to set the following directories in Windows:

- OpenVPN base directory: `C:\Program Files\OpenVPN`
- OpenVPN bin directory: `C:\Program Files\OpenVPN\bin`
- EasyRSA bin directory: `C:\Program Files\OpenVPN\easy-rsa\bin`

Why would you make the default directory for OpenVPN ` C:/Progra~1/Openvpn`?  The normal directory on most computers is `C:/Program Files/OpenVPN`.

Thank you.

**Comment by TinCanTech** [comment]
I have not made provision in the config file for paths to the files you require.

The reason to use `/Progra~1/` is because it is the `8.3` format, which does not allow for space characters.  Easy-TLS had some early issues with spaces in path, which may still be present.

You could try these options: 
```
-b|--base-dir=<DIR>    Path to OpenVPN base directory. (Windows Only)
                       Default: C:/Progra~1/OpenVPN
-o|--ovpnbin-dir=<DIR> Path to OpenVPN bin directory. (Windows Only)
                       Default: C:/Progra~1/OpenVPN/bin
-e|--ersabin-dir=<DIR> Path to Easy-RSA3 bin directory. (Windows Only)
                       Default: C:/Progra~1/Openvpn/easy-rsa/bin
```
Although, the command line becomes completely unwieldy.

Why do you need to set those options, where did you install OpenVPN ?

**Comment by xinthose** [comment]
OK.  I was trying the options without success.  I installed OpenVPN in the default location.

`easytls --ovpnbin-dir=C:/Program Files/OpenVPN/bin init-pki`

**Comment by TinCanTech** [comment]
What kind of error messages do you get ?

FYI: Every commit is tested on Windows, I also test locally.

**Comment by xinthose** [comment]
It still tries to use the default directory of `Progra~1/Openvpn`.

**Comment by TinCanTech** [comment]
Please, only try with master.

What happens if you do not specify the directory ? Does Easy-TLS not find Openvpn ?

**Comment by TinCanTech** [comment]
The only reason Easy-TLS required alternate binaries for Openvpn was that, during development, OpenVPN 2.5 was not available, so it was easier to build and install separately.  I fully intend to remove all these options eventually.

**Comment by xinthose** [comment]
OK.  I skipped the TLS part and am just using EasyRSA for the server.  I was getting a whole bunch of errors saying it could not find files in the three directories mentioned.  It always looked in `Progra~1`.

**Comment by TinCanTech** [comment]
It is not fixed, yet ..

I would be curious to see the output you get from Easy-TLS.

**Comment by xinthose** [comment]
OK.  I can run the command tomorrow hopefully and report back.

**Comment by TinCanTech** [comment]
Use a command like `./easyrsa show-ca` to **show** Easy-RSA works.<br>
Then use `./easytls init` and **show** the output of that too.

**Comment by xinthose** [comment]
``` shell
Welcome to the EasyRSA 3 Shell for Windows.
Easy-RSA 3 is available under a GNU GPLv2 license.

Invoke './easyrsa' to call the program. Without commands, help is displayed.

EasyRSA Shell
# easyrsa show-ca

Note: using Easy-RSA configuration from: C:/Users/TOMMIE HERRELL/Documents/EasyRSA-3.0.8/vars
Using SSL: openssl OpenSSL 1.1.0j  20 Nov 2018

Showing  details for 'ca'.
This file is stored at:
C:/Users/TOMMIE HERRELL/Documents/EasyRSA-3.0.8/pki/ca.crt

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            cf:d6:43:0f:69:e7:83:ff
    Signature Algorithm: sha256WithRSAEncryption
        Issuer:
            commonName                = portalogic
        Validity
            Not Before: Jan 13 19:23:29 2022 GMT
            Not After : Jan 11 19:23:29 2032 GMT
        Subject:
            commonName                = portalogic
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                4E:A3:E3:8A:42:8D:19:55:46:FB:D9:9E:64:50:CC:B0:95:82:F2:5F
            X509v3 Authority Key Identifier:
                keyid:4E:A3:E3:8A:42:8D:19:55:46:FB:D9:9E:64:50:CC:B0:95:82:F2:5F
                DirName:/CN=portalogic
                serial:CF:D6:43:0F:69:E7:83:FF

            X509v3 Basic Constraints:
                CA:TRUE
            X509v3 Key Usage:
                Certificate Sign, CRL Sign


EasyRSA Shell
# easytls init
Easy-TLS 2.8.0
OpenVPN

Error: EasyTLS tools will not function correctly in this path.
Note: Remove spaces from PATH using CD to select short name.

EasyRSA Shell
```

`C:\Users\Ada Dunsmoor\Documents\EasyRSA-3.0.8`

Is any of this information private?

**Comment by TinCanTech** [comment]
If you are concerned for privacy, you may also delete your edit history.

Basically, Easy-TLS does not work if you have a space in the path.

I need to sort this out but it will take some time.

For now, the option is to use either `C:\Program Files\Openvpn` (Which `easytls` will interpret as `C:/Progra~1/Openvpn`) or another path without a space in it.

**Comment by TinCanTech** [comment]
#260

**Comment by TinCanTech** [comment]
@xinthose If you would like to try it, all you need is `easytls` :cake:
