### ISSUE TITLE
./easytls: line 7: syntax error near unexpected token `newline' ./easytls: line 7: `<!DOCTYPE html>'

### ISSUE THREAD

**Issue by dannyolsen** [TinCanTech/easy-tls#277]
hi,

does anyone know how to fix this?

when typing ./easytls is get:

"
root@ubuntu:/easy-rsa# root@ubuntu:/easy-rsa# ./easytls
./easytls: line 7: syntax error near unexpected token `newline'
./easytls: line 7: `<!DOCTYPE html>'
"

Im running ubuntu on a raspberry 4

any help appreciated...

Danny

**Comment by TinCanTech** [comment]
The line in question is a comment, but it is wrapped in a heredoc. I can change this .. but what is your version of bash ?
