### ISSUE TITLE
v.2.7.0 on Windows 11 | "Missing: C:/Progra~1/Openvpn/bin/openssl.exe"

### ISSUE THREAD

**Issue by TheSwede86** [TinCanTech/easy-tls#306]
Microsoft Windows 11 
Version: 22H2
Build: 22621.2283

OpenVPN 2.6.6 installed at:
C:\Program Files\OpenVPN

easy-rsa (v.3.1.6) extracted at:
C:\Program Files\OpenVPN\easy-rsa

easy-tls (v.2.7.0) extracted at:
C:\Program Files\OpenVPN\easy-rsa
(so all the files are extracted in the root directory of "easy-rsa")

Hello,

Using these instructions:
https://community.openvpn.net/openvpn/wiki/EasyRSA3-OpenVPN-Howto
I am currently stuck at the following step:
`Initialise Easy-TLS:`

1) Starting CMD
2) `cd "C:\Program Files\OpenVPN\easy-rsa"`
3) `.\EasyRSA-Start.bat` (which starts the "EasyRSA Shell", subsequent commands are invoked in this shell)
4) `./easytls init-tls` returns:
```
Missing: C:/Progra~1/Openvpn/bin/openssl.exe
Errors occurred!
```

I tried to copy "openssl.exe" from `C:\Program Files\OpenVPN\easy-rsa` to `C:\Program Files\OpenVPN\bin` but then I received this error:
```
OPENSSL_Uplink(00007FF92A32CAC8,08): no OPENSSL_Applink
Easy-TLS 2.7.0
OpenVPN 2.6.6

Error: Missing or invalid OpenSSL:

```

I've tried checking this link:
https://github.com/TinCanTech/easy-tls/wiki/Windows-Requirements
which seems to indicate that the path `C:\Program Files\` should work even though it contain spaces.

Any ideas?

Best Regards

**Comment by TinCanTech** [comment]
@TheSwede86 Hi, by the look of your instructions, I think you are trying to use the OpenSSL version shipped with Easy-RSA by putting it into the `bin` directory of OpenVPN.  Which means you are mixing binary and DLL files that are not matched.

If that is the case then remove Easy-RSA and only use the version shipped with OpenVPN.

**Comment by TheSwede86** [comment]
> @TheSwede86 Hi, by the look of your instructions, I think you are trying to use the OpenSSL version shipped with Easy-RSA by putting it into the `bin` directory of OpenVPN. Which means you are mixing binary and DLL files that are not matched.
> 
> If that is the case then remove Easy-RSA and only use the version shipped with OpenVPN.

Thank you for your reply.

Thing is that the only `openssl.exe` I found in `C:\Program Files\OpenVPN` was the one in `C:\Program Files\OpenVPN\easy-rsa`.
I did a search for `openssl.exe` in `C:\Program Files\OpenVPN` and that was the only match I received.

I checked in the root of:
`C:\Program Files\`
and
`C:\Program Files (x86)\`
and couldn't find any directory named `OpenSSL` (if OpenVPN would install it to a separate directory).

**Comment by TinCanTech** [comment]
To use `easytls`, installing OpenVPN is a **hard** requirement.

When you install OpenVPN, select **Custom Installation** and select Easy-RSA to be installed with OpenVPN.

**Comment by TheSwede86** [comment]
> To use `easytls`, installing OpenVPN is a **hard** requirement.
> 
> When you install OpenVPN, select **Custom Installation** and select Easy-RSA to be installed with OpenVPN.

Thank you, I had OpenVPN installed but copied "easy-rsa" and "easy-tls" to that directory and that caused the error.
When installing "easy-rsa" when installing OpenVPN using the "Custom Installation"-alternative then "easy-tls" worked perfectly.
