### ISSUE TITLE
Error: Unsupported OpenSSL version: 3.2

### ISSUE THREAD

**Issue by Peuquet** [TinCanTech/easy-tls#310]
Hi,

Here's what I get with the latest OpenVPN version:

EasyRSA Shell
# ./easytls init-tls
Easy-TLS 2.7.0
OpenVPN 2.6.9
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
Error: Unsupported OpenSSL version: 3.2

Which version of OpenVPN are you supporting with Easy-TLS 2.7.0?

Best regards

**Comment by TinCanTech** [comment]
@Peuquet Thanks, I'll push an update for this.

**Comment by TinCanTech** [comment]
Fix: 0cfe916fb0f4ea16558f4c640caecd5b0b48cdad

**Comment by Peuquet** [comment]
Hi,

Many thanks, that works like a charm, including an iPhone client.

All the best

Le jeu. 22 févr. 2024 à 20:47, TinCanTech ***@***.***> a
écrit :
