### ISSUE TITLE
Unsupported OpenSSL version: 3.3

### ISSUE THREAD

**Issue by lumason** [TinCanTech/easy-tls#312]
# ./easytls init-tls
Easy-TLS 2.7.0
OpenVPN 2.6.11
OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)
Error: Unsupported OpenSSL version: 3.3

**Comment by TinCanTech** [comment]
@lumason Thanks for reporting this, I'll get it fixed.

**Comment by TinCanTech** [comment]
Closed via 66c3167085cd6334c04e5bcfeb3b9e7f3603f29e

**Comment by lumason** [comment]
@TinCanTech  Thank you so much for taking the time to fix the bug I submitted on Git. It's much appreciated!
