### ISSUE TITLE
./easytls init-tls OPENSSL_Uplink(00007FFFC7B4FAC8,08): no OPENSSL_Applink

### ISSUE THREAD

**Issue by yanother1** [TinCanTech/easy-tls#313]
I get the "OPENSSL_Uplink(00007FFFC7B4FAC8,08): no OPENSSL_Applink" error when doing init-tls
I am on Windows 10, OpenVPN 2.6.12, EasyRSA 3.1.7, and the most current easytls

_Here are my C:\Program Files\OpenVPN\easy-rsa directory contents:_

-rw-rw-rw-   1 user     group        1256 Aug 17 10:54 COPYING.html
-rw-rw-rw-   1 user     group        1305 Aug 17 10:54 COPYING.md
-rw-rw-rw-   1 user     group       11430 Aug 17 10:54 ChangeLog
-rwxrwxrwx   1 user     group          49 Aug 17 10:54 EasyRSA-Start.bat
drwxrwxrwx   1 user     group           0 Aug 17 10:54 Licensing
-rw-rw-rw-   1 user     group        4256 Aug 17 10:54 README-Windows.txt
-rw-rw-rw-   1 user     group        2464 Aug 17 10:54 README.html
-rw-rw-rw-   1 user     group        3477 Aug 17 10:54 README.quickstart.html
drwxrwxrwx   1 user     group           0 Aug 17 10:54 bin
drwxrwxrwx   1 user     group           0 Aug 17 10:54 doc
-rw-rw-rw-   1 user     group      189372 Aug 17 10:54 easyrsa
-rw-rw-rw-   1 user     group      274969 Aug 15 09:40 easytls
-rw-rw-rw-   1 user     group       40065 Aug 17 12:02 easytls-client-connect.sh
-rw-rw-rw-   1 user     group       21011 Aug 17 12:03 easytls-client-disconnect.sh
-rw-rw-rw-   1 user     group        6198 Aug 19 11:09 easytls-conntrac.lib
-rw-rw-rw-   1 user     group       37942 Aug 17 12:02 easytls-cryptv2-verify.sh
-rw-rw-rw-   1 user     group     6226757 Aug 17 10:54 libcrypto-3-x64.dll
-rw-rw-rw-   1 user     group     1081808 Aug 17 10:54 libssl-3-x64.dll
-rw-rw-rw-   1 user     group        5145 Aug 17 10:54 openssl-easyrsa.cnf
-rwxrwxrwx   1 user     group     1504088 Aug 17 10:54 openssl.exe
drwxrwxrwx   1 user     group           0 Aug 19 11:13 pki
-rw-rw-rw-   1 user     group        9223 Aug 17 11:24 vars
-rw-rw-rw-   1 user     group        9085 Aug 17 10:54 vars.example
drwxrwxrwx   1 user     group           0 Aug 17 10:54 x509-types

I had done the following commands successfully:
EasyRSA-Start.bat
./easyrsa build-ca nopass

I am at a loss, as I had done this a few years ago without issue.

TIA

**Comment by TinCanTech** [comment]
The EasyRSA Windows tools no longer work as expected, due to Windows _security_ changes. You need to use Linux now.

**Comment by yanother1** [comment]
Thanks for the quick reply!  Strange, I was almost sure that I used Windows 10 in the past.   If I can trouble you for a question:
Does the OpenVPN Client for Windows still work?

**Comment by TinCanTech** [comment]
> Does the OpenVPN Client for Windows still work?

Your GitHub bio states: " _Retired former software exec_ "
