### ISSUE TITLE
tls-crypt-v2-verify.sh - wrong path to crl.pem

### ISSUE THREAD

**Issue by hellkaim** [TinCanTech/easy-tls#70]
Hi, I am a bit new in GitHub so do not know correct way to bind my issue or propose a patch.

The issue is that in tls-crypt-v2-verify.sh line 456 is a following code
https://github.com/TinCanTech/easy-tls/blob/0d8b5a3e87afae4c53b9b308b2f63a5d77b0efce/tls-crypt-v2-verify.sh#L457

And it is wrong as in latest EasyRSA in the main script (easyrsa) line 1309 we have the following
https://github.com/OpenVPN/easy-rsa/blob/e68faed0a3832028ed2e9999cd2013d9664bd067/easyrsa3/easyrsa#L1309
`out_file="$EASYRSA_PKI/crl.pem"`

Easy to see. that Easy-RSA is generating file in .../easy-rsa/pki/crl.pem and EasyTLS expects it to be in .../easy-rsa/crl.pem

I think the simpliets will be to edit line 456 of tls-crypt-v2-verify.sh and make it look like
`crl_pem="$CA_DIR/pki/crl.pem"`

Do not blame me to much if I missed understood the concept.

**Comment by TinCanTech** [comment]
I'll have to dig into my mess but it does look like you are correct

Thank you very much for trying EasyTLS and reporting this issue.

**Comment by TinCanTech** [comment]
I do accept Pull Requests, if you chose to submit one for review.

**Comment by TinCanTech** [comment]
In fact, the path in `tls-crypt-v2-verify.sh` to `crl.pem` is correct.

`$CA_DIR` is the path where `ca.crt` is located, this is equivalent to `$EASYRSA_PKI`.
It is also the same directory where `crl.pem` is created by EasyRSA.
